Traceback (most recent call last):
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

#from sar_geometry import *
#from sar_functions import *
#from supplemental import *
import sys
sys.path.insert(1, '/Users/bhills/Software/squintsar/squintsar/lib/')
from supplemental import calc_dist, dB, r2p
from sar_geometry import sar_raybend, get_depth_dist
from sar_functions import matched_filter
from squintsar import sar_extent, fill_reference_array, sar_compression
------------------


Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3553[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0;36m  Cell [0;32mIn[1], line 12[0;36m
[0;31m    from squintsar import sar_extent, fill_reference_array, sar_compression[0;36m

[0;36m  File [0;32m~/Software/squintsar/squintsar/lib/squintsar.py:11[0;36m[0m
[0;31m    <<<<<<< Updated upstream[0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


